### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [HarryET/custodi#18]

**Comment by HarryET** [comment]
Will discuss in discord, as this needs approval from all team members - who have contributed to this point

**Comment by HarryET** [comment]
Proposed GPLv3 licence, once I have received confirmation from:
@Isaiah-Hamilton 
@VictorPeralta 
@aidenschrock 

This will be added to the project officially.

**Comment by aidenschrock** [comment]
Looks good 👍

**Comment by Isaiah-Hamilton** [comment]
Looks good 👍

**Comment by VictorPeralta** [comment]
:+1:

**Comment by Teikidisi** [comment]
its fine by me
