### ISSUE TITLE
[bug] redirect link broken

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [HarryET/custodi#19]
When canceling on any Oauth provider, the provider redirects to `localhost`.

For example when canceling with GitHub provider you get redirected.

https://user-images.githubusercontent.com/70828596/145073502-5e6e41ab-c062-486a-906f-eab57b80b420.MOV

To reproduce:
1. Go to `/login`
2. Click any Oauth provider
3. Cancel with Oauth provider

**Comment by HarryET** [comment]
> When canceling Oauth provider, redirects to `localhost`
> 
> More info later

Cancelling in what context? and which provider?

**Comment by Isaiah-Hamilton** [comment]
Fixed with #42
